name:                blockswap-PoN
version:             0.1.0.0
github:              "githubuser/blockswap-PoN"
license:             BSD3
author:              "Fabrizio Genovese and Philipp Zahn"
maintainer:          "philipp@20squares.xyz"
copyright:           "2023 Fabrizio Genovese and Philipp Zahn"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blockswap-PoN#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- extra
- mtl
- open-games-hs
- optics
- probability
- unordered-containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  blockswap-PoN-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockswap-PoN

tests:
  blockswap-PoN-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blockswap-PoN
